version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    - goheader
    - misspell
    - nilnil
    - paralleltest
    - revive
  settings:
    goheader:
      template: |-
        Copyright {{ YEAR }} LLC "Ozon Technologies".
        SPDX-License-Identifier: Apache-2.0

formatters:
  enable:
    - goimports
    - gofmt
  settings:
    goimports:
      local-prefixes:
        - github.com/ozontech/ch-rollup
